### Principle Component Analysis

In [1]:
import numpy as np

In [2]:
### Data
features = X = np.array([[4, 8, 13, 7], [11, 4, 5, 14]])

In [3]:
X

array([[ 4,  8, 13,  7],
       [11,  4,  5, 14]])

In [4]:
features

array([[ 4,  8, 13,  7],
       [11,  4,  5, 14]])

In [5]:
X.shape

(2, 4)

## Step 1: Calculate Mean

In [6]:
mean_X1 = np.mean(X[0])
mean_X2 = np.mean(X[1])

In [7]:
X[0]

array([ 4,  8, 13,  7])

In [8]:
mean_X1

8.0

In [10]:
mean_X2

8.5

### Step 2: Calculate Covariance Matrix

$\mathbf{X} =
\begin{bmatrix}
 Cov(x_1 x_1) & Cov(x_1 x_2) \\
 Cov(x_2 x_1) & Cov(x_2 x_2) \\
\end{bmatrix}
$

$Cov(\mathbf{x_1,x_1}) = \frac{1}{m-1} \sum\limits_{k = 1}^{m} (x_1k-x_1\mu)(x_1k-x_1\mu)$ \
$Cov(\mathbf{x_1,x_2}) = \frac{1}{m-1} \sum\limits_{k = 1}^{m} (x_1k-x_1\mu)(x_2k-x_2\mu)$ \
$Cov(\mathbf{x_2,x_1}) = \frac{1}{m-1} \sum\limits_{k = 1}^{m} (x_2k-x_2\mu)(x_1k-x_1\mu)$ \
$Cov(\mathbf{x_2,x_2}) = \frac{1}{m-1} \sum\limits_{k = 1}^{m} (x_2k-x_2\mu)(x_2k-x_2\mu)$

In [23]:
Cov_x1x1 = 1/(X.shape[1]-1) * ((X[0][0] - mean_X1) * (X[0][0] - mean_X1) +
                               (X[0][1] - mean_X1) * (X[0][1] - mean_X1) +
                               (X[0][2] - mean_X1) * (X[0][2] - mean_X1) +
                               (X[0][3] - mean_X1) * (X[0][3] - mean_X1))

In [24]:
Cov_x1x1

14.0

In [19]:
Cov_x1x2 = 1/(X.shape[1]-1) * ((X[0][0] - mean_X1) * (X[1][0] - mean_X2) +
                               (X[0][1] - mean_X1) * (X[1][1] - mean_X2) +
                               (X[0][2] - mean_X1) * (X[1][2] - mean_X2) +
                               (X[0][3] - mean_X1) * (X[1][3] - mean_X2))

In [27]:
Cov_x2x1 = 1/(X.shape[1]-1) * ((X[1][0] - mean_X2) * (X[0][0] - mean_X1) +
                               (X[1][1] - mean_X2) * (X[0][1] - mean_X1) +
                               (X[1][2] - mean_X2) * (X[0][2] - mean_X1) +
                               (X[1][3] - mean_X2) * (X[0][3] - mean_X1))

In [28]:
Cov_x2x1

-11.0

In [29]:
Cov_x2x2 = 1/(X.shape[1]-1) * ((X[1][0] - mean_X2) * (X[1][0] - mean_X2) +
                               (X[1][1] - mean_X2) * (X[1][1] - mean_X2) +
                               (X[1][2] - mean_X2) * (X[1][2] - mean_X2) +
                               (X[1][3] - mean_X2) * (X[1][3] - mean_X2))

In [30]:
Cov_x2x2

23.0

In [31]:
## Covariance Matrix
S = np.array([[Cov_x1x1, Cov_x1x2], [Cov_x2x1, Cov_x2x2]])

In [32]:
S

array([[ 14., -11.],
       [-11.,  23.]])

### Step 3: Calculate Eigenvalues of the covariance matrix

$I = \begin{vmatrix} {1} & {0} \\ {0} & {1} \end{vmatrix}$  

$\lambda I = \begin{vmatrix} {\lambda} & {0} \\ {0} & {\lambda} \end{vmatrix}$  

$det(\mathbf{S - \lambda I}) = 0$  

$\begin{vmatrix} {14-\lambda} & {-11} \\ {-11} & {23-\lambda} \end{vmatrix} = 0$  

$\mathbf{(14 - \lambda)(23-\lambda) - (-11)(-11)} = 0$  

$\lambda^{2} - 37 \lambda + 201 = 0$  

$\lambda = (30.3849, 6.151)$

### Step4: Computation of eigenvectors

$\mathbf{U} =  \begin{bmatrix} u_{1} \\  u_{2} \\ \end{bmatrix}$

$\mathbf({S - \lambda I}U) = \begin{bmatrix} {0} \\  {0} \\ \end{bmatrix}$  

$\begin{bmatrix} {14-\lambda} & {-11} \\ {-11} & {23-\lambda} \end{bmatrix} \begin{bmatrix} u_{1} \\  u_{2} \\ \end{bmatrix} = \begin{bmatrix} {0} \\  {0} \\ \end{bmatrix}$  

$\begin{bmatrix} {(14-\lambda)u_{1}} & {-11}u_{2} \\ {-11}u_{1} & {(23-\lambda)u_{2}} \end{bmatrix}  = \begin{bmatrix} {0} \\  {0} \\ \end{bmatrix}$  

$\mathbf(14-\lambda) u_{1} - 11 u_{2} = 0$  

$\frac {u{1}}{11} = \frac {u{2}}{14-\lambda} = t$  

$u_{1} = 11t, \ u_{2} = (14-\lambda) t$  

$\mathbf{U_{1}} =  \begin{bmatrix} {11} \\  {14 - \lambda _{1}} \\ \end{bmatrix}$

$\mathbf- 11 u_{1} + {(23-\lambda) u_{2}}  = 0$  

$\frac {u{1}}{23-\lambda} = \frac {u{2}}{11} = t$

$u_{1} = (23 - \lambda)t, \ u_{2} = 11 t$  

$\mathbf{U_{2}} =  \begin{bmatrix} {23 - \lambda _{2}} \\  {11} \\ \end{bmatrix}$

$\lambda = (30.3849, 6.151) \ for \ PC \ consider \ largest \ eigenvalue \ and \ for \ second \ PC \ use \ the \ next \ one$


### Step 5: Unit eigenvector

$length \ of \ U1 = \mathbf{|| U_{1} ||} =  \sqrt{(11^{2} + (14-\lambda _{1} ^{2})} \ = 19.7348$  

$\mathbf{e_{1}} =  \begin{bmatrix} \frac {{11}}{|| U_{1} ||} \\  \frac {{(14 - \lambda)}}{|| U_{1} ||} \end{bmatrix}$  

$\mathbf{e_{1}} =  \begin{bmatrix} \frac {{11}}{19.7348} \\  \frac {{(14 - 30.3849)}}{19.7348} \end{bmatrix}$   

$\mathbf{e_{1}} =  \begin{bmatrix} 0.5574 \\  -0.8303 \end{bmatrix}$

$using \ \lambda_{2} = 6.6151 $  

$\mathbf{e_{2}} =  \begin{bmatrix} 0.8303 \\  0.5574 \end{bmatrix}$


### Step 6: Compute first Principle Component

$\mathbf{e_{1}^{T}}\begin{bmatrix} (x_1k-x_1\mu)\\  (x_2k-x_2\mu) \end{bmatrix}$  

$=  \begin{bmatrix} (0.5574-0.8303)\end{bmatrix} \begin{bmatrix} (x_{11}-x_1\mu)\\  (x_{21}-x_2\mu) \end{bmatrix}$


$=  (0.5574)(x_{11}-x_1\mu) - 0.8303(x_{21}-x_2\mu)$  

$=  (0.5574)(4-8) - 0.8303(1-8.5)$  

$=  -4.30535$

$=  (0.5574)(x_{12}-x_1\mu) - 0.8303(x_{22}-x_2\mu) \ = 3.7361$  

$=  (0.5574)(x_{13}-x_1\mu) - 0.8303(x_{23}-x_2\mu) \ = 5.6928$  

$=  (0.5574)(x_{14}-x_1\mu) - 0.8303(x_{24}-x_2\mu) \ = -5.1238$  



In [36]:
from tabulate import tabulate

# Define the table data
table_data = [
    ["Features", "Instance 1", "Instance 2", "Instance 3", "Instance 4"],
    ["X1", "4", "8", "13", "7"],
    ["X2", "11", "4", "5", "14"],
    ["First Principle Components", "-4.30535", "3.7361", "5.6928", "-5.1238"]
]

# Generate the table
table = tabulate(table_data, headers='firstrow', tablefmt='pipe')
print(table)

| Features                   |   Instance 1 |   Instance 2 |   Instance 3 |   Instance 4 |
|:---------------------------|-------------:|-------------:|-------------:|-------------:|
| X1                         |      4       |       8      |      13      |       7      |
| X2                         |     11       |       4      |       5      |      14      |
| First Principle Components |     -4.30535 |       3.7361 |       5.6928 |      -5.1238 |
