In [72]:
import scipy.io
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline

In [79]:
K = 3
X = np.array([
      [5.1, 3.5, 1.4, 0.2], [4.9, 3, 1.4, 0.2], [4.7, 3.2, 1.3, 0.2], [4.6, 3.1, 1.5, 0.2], [5, 3.6, 1.4, 0.2],
      [7, 3.2, 4.7, 1.4], [6.4, 3.2, 4.5, 1.5], [6.9, 3.1, 4.9, 1.5], [5.5, 2.3, 4, 1.3], [6.5, 2.8, 4.6, 1.5],
      [6.3, 3.3, 6, 2.5], [5.8, 2.7, 5.1, 1.9], [7.1, 3, 5.9, 2.1], [6.3, 2.9, 5.6, 1.8], [6.5, 3, 5.8, 2.2]])
initial_centroids = np.array([[6.3, 3.3, 6, 2.5], [5.8, 2.7, 5.1, 1.9], [7.1, 3, 5.9, 2.1]])

In [80]:
initial_centroids

array([[6.3, 3.3, 6. , 2.5],
       [5.8, 2.7, 5.1, 1.9],
       [7.1, 3. , 5.9, 2.1]])

In [81]:
X[0,:]

array([5.1, 3.5, 1.4, 0.2])

In [82]:
np.argmin(np.sqrt(np.sum((X[5,:]-initial_centroids)**2, axis=1)))+1

3

In [83]:
def find_closest_centroid(X, centroids):
    idx = np.zeros((X.shape[0],1))
    for i in range(X.shape[0]):
        idx[i] = np.argmin(np.sqrt(np.sum((X[i,:]-centroids)**2, axis=1)))+1
        #print(idx[i])
    return idx

In [84]:
def compute_centroids(X, idx, K):
    centroids = np.zeros((K, X.shape[1]))
    for i in range(K):
        centroids[i,:] = np.mean(X[(idx==i+1).T[0], :], axis=0)
        
        #print('X[(idx==i+1).T[0] {} centroids[i,:] {}'.format(X[(idx==i+1).T[0], :], centroids[i,:]))
    return centroids

In [85]:
clusters = find_closest_centroid(X, initial_centroids)
for i in range (X.shape[0]):
    print('X {} cluster {}'.format(X[i], clusters[i]))

new_centroids = compute_centroids(X, clusters, K)
print(new_centroids)

X [5.1 3.5 1.4 0.2] cluster [2.]
X [4.9 3.  1.4 0.2] cluster [2.]
X [4.7 3.2 1.3 0.2] cluster [2.]
X [4.6 3.1 1.5 0.2] cluster [2.]
X [5.  3.6 1.4 0.2] cluster [2.]
X [7.  3.2 4.7 1.4] cluster [3.]
X [6.4 3.2 4.5 1.5] cluster [2.]
X [6.9 3.1 4.9 1.5] cluster [3.]
X [5.5 2.3 4.  1.3] cluster [2.]
X [6.5 2.8 4.6 1.5] cluster [2.]
X [6.3 3.3 6.  2.5] cluster [1.]
X [5.8 2.7 5.1 1.9] cluster [2.]
X [7.1 3.  5.9 2.1] cluster [3.]
X [6.3 2.9 5.6 1.8] cluster [2.]
X [6.5 3.  5.8 2.2] cluster [1.]
[[6.4        3.15       5.9        2.35      ]
 [5.48       3.03       3.08       0.9       ]
 [7.         3.1        5.16666667 1.66666667]]


In [86]:
print(X[(clusters==0+1).T[0], :])
print(np.mean(X[(clusters==0+1).T[0], :], axis=0))

[[6.3 3.3 6.  2.5]
 [6.5 3.  5.8 2.2]]
[6.4  3.15 5.9  2.35]


In [87]:
clusters = find_closest_centroid(X, new_centroids)
for i in range (X.shape[0]):
    print('X {} cluster {}'.format(X[i], clusters[i]))

new_centroids = compute_centroids(X, clusters, K)
print(new_centroids)

X [5.1 3.5 1.4 0.2] cluster [2.]
X [4.9 3.  1.4 0.2] cluster [2.]
X [4.7 3.2 1.3 0.2] cluster [2.]
X [4.6 3.1 1.5 0.2] cluster [2.]
X [5.  3.6 1.4 0.2] cluster [2.]
X [7.  3.2 4.7 1.4] cluster [3.]
X [6.4 3.2 4.5 1.5] cluster [3.]
X [6.9 3.1 4.9 1.5] cluster [3.]
X [5.5 2.3 4.  1.3] cluster [2.]
X [6.5 2.8 4.6 1.5] cluster [3.]
X [6.3 3.3 6.  2.5] cluster [1.]
X [5.8 2.7 5.1 1.9] cluster [1.]
X [7.1 3.  5.9 2.1] cluster [1.]
X [6.3 2.9 5.6 1.8] cluster [1.]
X [6.5 3.  5.8 2.2] cluster [1.]
[[6.4        2.98       5.68       2.1       ]
 [4.96666667 3.11666667 1.83333333 0.38333333]
 [6.7        3.075      4.675      1.475     ]]


In [88]:
clusters = find_closest_centroid(X, new_centroids)
for i in range (X.shape[0]):
    print('X {} cluster {}'.format(X[i], clusters[i]))

new_centroids = compute_centroids(X, clusters, K)
print(new_centroids)

X [5.1 3.5 1.4 0.2] cluster [2.]
X [4.9 3.  1.4 0.2] cluster [2.]
X [4.7 3.2 1.3 0.2] cluster [2.]
X [4.6 3.1 1.5 0.2] cluster [2.]
X [5.  3.6 1.4 0.2] cluster [2.]
X [7.  3.2 4.7 1.4] cluster [3.]
X [6.4 3.2 4.5 1.5] cluster [3.]
X [6.9 3.1 4.9 1.5] cluster [3.]
X [5.5 2.3 4.  1.3] cluster [3.]
X [6.5 2.8 4.6 1.5] cluster [3.]
X [6.3 3.3 6.  2.5] cluster [1.]
X [5.8 2.7 5.1 1.9] cluster [1.]
X [7.1 3.  5.9 2.1] cluster [1.]
X [6.3 2.9 5.6 1.8] cluster [1.]
X [6.5 3.  5.8 2.2] cluster [1.]
[[6.4  2.98 5.68 2.1 ]
 [4.86 3.28 1.4  0.2 ]
 [6.46 2.92 4.54 1.44]]
